### ISSUE TITLE
Remove direct imports in (pre)release files (?)

### ISSUE THREAD

**Issue by pbuttigieg** [AgriculturalSemantics/agro#1]
Annotation properties, subclass assertions, etc are replicated by imports listed as direct imports in Protege. In the release files, we don't really need to pull in the imports directly (similar to ENVO). We'll try to ensure that direct imports are omitted from the release files.

We'll watch the test release processes and try to resolve this in the Makefile recipes.

Replicates may persist in the editors version, but I don't think this is a cause from concern.

**Comment by marieALaporte** [comment]
I think this issue has been resolved so I close it for now
