### ISSUE TITLE
[Revise text def] number of square meter harvested

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#100]
**AgrO term (ID and Label)**
AGRO:00000558
number of square meter harvested

**Suggested revision of textual definition. Please include a source, like a website**
Current def: Number of different crop used in an experiment.
Proposed def: pending...

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by celineaubert** [comment]
def: number of square meters of agricultural field or plot harvested
