### ISSUE TITLE
[Revise text def] ridge height

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#101]
**AgrO term (ID and Label)**
[ridge height](http://purl.obolibrary.org/obo/AGRO_00000544)

**Suggested revision of textual definition. Please include a source, like a website**
Revise annotation dc:description to IAO_0000115, removing current IAO_0000115

**Your nano-attribution (ORCID)**

**Comment by celineaubert** [comment]
def could be: Distance between the top and the bottom of a ridge.
