### ISSUE TITLE
[Revise text def] boom sprayer

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#102]
**AgrO term (ID and Label)**
[boom sprayer](http://purl.obolibrary.org/obo/AGRO_00000539)

**Suggested revision of textual definition. Please include a source, like a website**
Current def: An implement that is used to spray liquid and is help in the hand. It usually has an air pump which compresses air into the tanks and pressurizes the liquid to spray. [duplicate to [hand sprayer](http://purl.obolibrary.org/obo/AGRO_00000144)]
Proposed def: pending...

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by celineaubert** [comment]
possible def: An implement which is a pipe with attached nozzles for distributing spray. Is has a list of system components that work together to deliver the spray fluid.

https://en.wikipedia.org/wiki/Sprayer
https://www.google.com/patents/US8420070
