### ISSUE TITLE
[Revise text def] ridge width

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#103]
**AgrO term (ID and Label)**
[ridge width](http://purl.obolibrary.org/obo/AGRO_00000543)

Suggested revision of textual definition. Please include a source, like a website
Revise annotation dc:description to IAO_0000115, removing current IAO_0000115

**Your nano-attribution (ORCID)**

**Comment by celineaubert** [comment]
def for this term should be: ''A width entity that inheres in some ridge''. No reference for that.
