### ISSUE TITLE
[Revise text def] distance between plants

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#105]
**AgrO term (ID and Label)**
[distance between plants](http://purl.obolibrary.org/obo/AGRO_00000316)

**Suggested revision of textual definition. Please include a source, like a website**
Multiple definitions, remove one
"The distance of a whole plant"
"Distance between two rows." [covered by [distance between rows](http://purl.obolibrary.org/obo/AGRO_00000318)]

**Your nano-attribution (ORCID)**

**Comment by celineaubert** [comment]
def should be: The distance between two plants
