### ISSUE TITLE
[Revise text def] distance between rows

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#106]
**AgrO term (ID and Label)**
[distance between rows](http://purl.obolibrary.org/obo/AGRO_00000318)

**Suggested revision of textual definition. Please include a source, like a website**
Duplicate definitions, requires revised definition 
"Average distance between plants in a same row."
"The distance of a row"
Proposed def: The distance between two rows.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by celineaubert** [comment]
agree
