### ISSUE TITLE
[Revise text def] crop residue area density

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#107]
**AgrO term (ID and Label)**
[crop residue area density](http://purl.obolibrary.org/obo/AGRO_00000444)

**Suggested revision of textual definition. Please include a source, like a website**
Duplicate definition
"An area density quality which inheres in above-ground crop residue by virtue of some influence exerted by the mass of above-ground crop residue applied in a given surface area."
"The area density of a crop residue" [remove]

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by celineaubert** [comment]
agree

**Comment by KrishnaTO** [comment]
Check pattern duplication for QA
