### ISSUE TITLE
[Revise logical def] total number of puddling passes

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#112]
**AgrO term (ID and Label)**
[total number of puddling passes](http://purl.obolibrary.org/obo/AGRO_00010024)

**Suggested revision of logical definition**
Incorrect oboInOwl:hasExactSynonym
Proposed: "total number of puddling passes"

**Your nano-attribution (ORCID)**

**Comment by celineaubert** [comment]
Sorry, I don't understand your note. Could you explain the issue, please?

**Comment by KrishnaTO** [comment]
For this issue, the term had an incorrect synonym: "[total number of land levelling passes](https://www.ebi.ac.uk/ols/ontologies/agro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FAGRO_00010024)". Instead the proposed was...proposed above.

**Comment by celineaubert** [comment]
the proposed synonym is exactly similar to the term. 
the synonym could be : number of puddling passes

**Comment by KrishnaTO** [comment]
Good catch, missed it myself. 
Any issues with exchanging revised synonym with label as well?

**Current term**  
label: [total number of puddling passes](http://purl.obolibrary.org/obo/AGRO_00010024); 
synonym: number of puddling passes

**Updated term**
label: [number of puddling passes](http://purl.obolibrary.org/obo/AGRO_00010024); 
synonym: total number of puddling passes

**Comment by celineaubert** [comment]
I was also thinking about it. It is a good suggestion. 
Could you also modify the other ''total number of..'' to ''number of ...'' with '' total number of ..'' as a synonym, so all the Occurrence terms look similar?
![image](https://user-images.githubusercontent.com/14092820/138289133-6066da70-4f0a-40e1-a676-0f88da332e50.png)
