### ISSUE TITLE
[Revise logical def] Missing property IAO_0000115 for list of terms

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#113]
**AgrO term (ID and Label)**

- [x] subsurface textile irrigation process
- [x] mechanical pest removal process
- [x] crop residue
- [x] weight loss on ignition method
- [x] agricultural implement
- [x] soil profile altitude
- [x] limbing
- [x] haymaking process
- [x] windrowing
- [x] baling process
- [x] trussing process
- [x] storage process
- [x] cutting process
- [x] tedder
- [x] combine harvester
- [x] lifting process
- [x] dessication process
- [x] seed per meter square
- [x] seed per acre
- [x] row per plot
- [x] row per meter square
- [x] row per foot square
- [x] row per acre
- [x] row per hectare
- [x] plants per hill
- [x] plants per row
- [x] plants per square meter
- [x] plants per hectare
- [x] plants per pot
- [x] ridging process
- [x] land clearing process
- [x] animal manure area density
- [x] sustainable agriculture process
- [x] intercropping
- [x] mixed intercropping
- [x] row intercropping
- [x] within row intercropping
- [x] relay cropping
- [x] sequential intercropping
- [x] strip intercropping
- [x] land clearing date
- [x] slash-and-burn process
- [x] slash-and-remove process
- [x] rock crushing process
- [x] cut and grind process
- [x] pile and burn process
- [x] land burning process
- [x] rock removal process
- [x] roots crushing process
- [x] ridging date
- [x] ridging implement
- [x] ridging device mounted on planting implement
- [x] crop residue moisture
- [x] sprayer
- [x] forage harvester
- [x] reapper
- [x] digger
- [x] distance between ridges
- [x] aboveground biomass
- [x] below-ground biomass
- [x] seedling
- [x] rainfed process
- [x] jab planter
- [x] moist
- [x] crop residue removal process
- [x] plants per foot square
- [x] plants per plot
- [x] harvest cut height
- [x] pesticide amount
- [x] number of pesticide application
- [x] pesticide application date
- [x] weeding chemical amount
- [x] distance between the water source and the field
- [x] controlled traffic farming
- [x] pruning
- [x] renewal pruning
- [x] GPS coordinates
- [x] GPS coordinates of a field
- [x] field latitude coordinate
- [x] field longitude coordinate
- [x] alley cropping
- [x] silvopasture
- [x] multistrata agroforestry
- [x] tree prunings
- [x] agroforestry fallow
- [x] agroforestry
- [x] agrisilviculture
- [x] deficit irrigation process
- [x] alternate partial rootzone irrigation process
- [x] supplemental irrigation
- [x] water harvesting
- [x] water tank
- [x] grass strip
- [x] weed puller
- [x] mower
- [x] raised seedbed
- [x] water pressure spraying weeding process
- [x] crop yield experiment
- [x] agricultural experimental multiplot
- [ ] net plot
- [ ] gros plot

Review terms
- [ ] milimeter per plot
- [ ] inch per plot

Objects
- [ ] has method
- [ ] measurement method of
- [ ] has start date
- [ ] has end date

Annotation Property
- [ ] preferred fieldbook label

**Suggested revision of logical definition**
Potential fixes include:
- change description-equivalent properties to IAO_0000115
- add appropriate IAO_0000115

**Your nano-attribution (ORCID)**

**Comment by KrishnaTO** [comment]
Need further review on definitions for the open terms

@marieALaporte @celineaubert

**Comment by KrishnaTO** [comment]
Compiling commits into https://github.com/KrishnaTO/agro/tree/ROBOT-issues

**Comment by KrishnaTO** [comment]
Created issues #114 #115 #116 #117 #118 #119 #120, from remaining terms 

-  net plot
-  gros plot
-  milimeter per plot
-  inch per plot
-  has method
-  measurement method of
-  has start date
-  has end date
-  preferred fieldbook label

Will make PR to close

**Comment by celineaubert** [comment]
I might have forgotten to use IAO_0000115 for those terms and have added their definition under dc: description
