### ISSUE TITLE
[Obsolete] millimeter per plot ; inch per plot

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#116]
**AgrO term (ID and Label)**
[millimeter per plot](http://purl.obolibrary.org/obo/AGRO_00000553)
[inch per plot](http://purl.obolibrary.org/obo/AGRO_00000555)

**Reason for deprecation**
Need to revisit due to ambiguous interpretation and definition not provided. Term is subclass of `area density unit`, but refers to non-weight unit per area (density being mass per volume).

**Suggested term to consider**
[plot area](http://purl.obolibrary.org/obo/AGRO_00000302)?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by celineaubert** [comment]
Hi Krishna, 
This unit is used to measure precipitation (in millimeter per plot of inch per plot). This is a height of water per area. It is an ambiguous unit, but widely used (if not always used to talk about precipitation) and totally different from plot area. If you are able to find a better class for it, please move it, but do not obsolete those terms.

**Comment by KrishnaTO** [comment]
Also need to determine `total irrigation amount per plot` = ~`rain amount per plot` + `irrigation amount per plot`

In order to measure the amount of water added, as desired in this term, the inputs are 'irrigation' (issue #5 ) and 'rain'
Thus, the addition of quantity metrics by each method is required:

[water-based rainfall](http://purl.obolibrary.org/obo/ENVO_01000830)

- Rain amount per plot

Irrigation

- [irrigation water quantity](http://purl.obolibrary.org/obo/AGRO_00000010) (Note: requires relation with length-based measurement method and a revised definition as noted in term) (Related issue #17 )

Then, we can determine the water amount per plot as the considered term expects (in inches and mm). 

[inch per plot](http://purl.obolibrary.org/obo/AGRO_00000555)

- Rain amount per plot `and` [irrigation water quantity](http://purl.obolibrary.org/obo/AGRO_00000010)

**Comment by KrishnaTO** [comment]
@celineaubert Please review if we should keep the synonym in `irrigation water quantity`

**Comment by celineaubert** [comment]
no need to add mm/plot and inch/plot classes

-  total irrigation amount per plot = total irrigation water added during the experiment duration (rain water in not taken into account). Irrigation is done more than once during a cropping season, therefore agronomists measure ''irrigation amount'' for a single irrigation process and ''irrigation amount'' corresponding to all the irrigation processes done during the experiment.

**Comment by KrishnaTO** [comment]
In which case, should we obsolete the millimeter per plot and inch per plot units, in favour of unit suggestions from #5 ?
> Units are: mm, m3, m3/ha (if it exists in UO)

**Comment by celineaubert** [comment]
Hi Krishna, yes, sorry I forgot the classes were already existing in AgrO.

**Comment by KrishnaTO** [comment]
@celineaubert done, please review PR #136 for changes.
