### ISSUE TITLE
[Def] AGRO:00000145 airblast sprayer

### ISSUE THREAD

**Issue by marieALaporte** [AgriculturalSemantics/agro#128]
### AgrO term

AGRO:00000145 airblast sprayer

### Suggested revision of textual definition

There is a new line character in the definition. Should be removed

### Your nano-attribution (ORCID)

https://orcid.org/0000-0002-8461-9745

**Comment by celineaubert** [comment]
Not sure if this is related to the suggested revision, but it will be good to remove the extra ''d''
![image](https://user-images.githubusercontent.com/14092820/139827924-4a5fc951-cf58-408c-ae13-89a13cf57cc9.png)
