### ISSUE TITLE
reduced soil layer needs a definition in the deep placement class

### ISSUE THREAD

**Issue by celineaubert** [AgriculturalSemantics/agro#13]
It is not clear what is the ''reduced soil layer''. Need to find a definition.

**Comment by cmungall** [comment]
How should we coordinate representation of soil types in ENVO with AGRO?

**Comment by pbuttigieg** [comment]
Our last position was that classes like this one are of general interest,
and thus should be requested in / moved to ENVO. Terms which are clearly
agronomy or agriculture related (like fertilizer bearing soil) can be in
AgrO.

Celine, we should go through your new additions soon and realign.

**Comment by celineaubert** [comment]
class not in AgrO anymore
