### ISSUE TITLE
NTR: live fences

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#147]
Term: live fences
Definition: Fences established by planting large cuttings, that easily produce roots and on which several strings of wire are attached with the obvious purpose of keeping livestock in or out
Source: Harvey, C.A., Villanueva, C., Villacís, J., Chacón, M., Muñoz, D., López, M., Ibrahim, M., Gómez, R., Taylor, R., Martinez, J. and Navas, A., 2005. Contribution of live fences to the ecological integrity of agricultural landscapes. Agriculture, ecosystems & environment, 111(1-4), pp.200-230.
ecological integrity of agricultural
landscapes
Parent: AGRO:00000516
Related: AGRO:00000584, trees and crops, trees on crop land , zoned, on boundaries, live fences
ORCID: https://orcid.org/0000-0003-3985-4911

**Comment by celineaubert** [comment]
I suggest to use this term as a parent: http://purl.obolibrary.org/obo/ENVO_01000468 (fence)

**Comment by marieALaporte** [comment]
term created
