### ISSUE TITLE
NTR: boundary planting

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#148]
Term: boundary planting 
Definition: 
Source: Sinclair, F.L., 1999. A general classification of agroforestry practice. Agroforestry systems, 46(2), pp.161-180.
Parent: AGRO:00000516
Related: AGRO:00000584, trees and crops, trees on crop land , zoned, on boundaries, boundary planting
ORCID: https://orcid.org/0000-0003-3985-4911

**Comment by celineaubert** [comment]
Definition: Live fence made of trees. Boundary planting are used to delimitate	property,	agricultural fields, pastures, roads	or	any	other place where fences might be located.

Source: Baker,	K.,	Baumann,	D.,	Michaud,	J.S.,	van	Mossel-Forrester,	B., 2014. Technical	Specification Boundary	Planting. Registered	Plan	Vivo	Project: The	CommuniTree	Carbon	Project. 64p. URL: https://takingroot.org/wp-content/uploads/2015/04/takingroot-boundary-planting.pdf


Parent: Live fence
exact syn: barrier planting, Trees on boundaries

**Comment by KrishnaTO** [comment]
updated per comments
