### ISSUE TITLE
Add types of grazing management

### ISSUE THREAD

**Issue by cmungall** [AgriculturalSemantics/agro#16]
Even though the current focus of AgrO appears to be crops, this is the correct ontology for grazing techniques.

I would model this as 'regulation of grazing', where grazing is from an ontology like NBO, and the management is done by humans. We would have different subtypes for different practices, e.g. so called holistic grazing.

**Comment by pbuttigieg** [comment]
Sounds right, similar to ecosystem processes vs ecosystem services in EnvO
and SDGIO, resp.

**Comment by celineaubert** [comment]
`regulation of grazing` has been added in agro-edit.owl as `AGRO_00000426` with the data-cross-reference to AGROVOC : http://aims.fao.org/aos/agrovoc/c_3367.
Other grazing management practices have been added to `agro-edit.owl` under the main classe `regulation of grazing`

**Comment by cmungall** [comment]
actually, modeling this as a system may have some advantages, particularly for alignment to agrovoc:

```
  is_a http://aims.fao.org/aos/agrovoc/c_2841 ! feeding systems
   is_a http://aims.fao.org/aos/agrovoc/c_19085 ! zero grazing *** 
   is_a http://aims.fao.org/aos/agrovoc/c_3367 ! grazing systems *** 
    is_a http://aims.fao.org/aos/agrovoc/c_10034 ! common grazing *** 
    is_a http://aims.fao.org/aos/agrovoc/c_14187 ! selective grazing *** 
    is_a http://aims.fao.org/aos/agrovoc/c_3046 ! forest grazing *** 
    is_a http://aims.fao.org/aos/agrovoc/c_36542 ! continuous grazing *** 
    is_a http://aims.fao.org/aos/agrovoc/c_4875 ! mixed grazing *** 
    is_a http://aims.fao.org/aos/agrovoc/c_5497 ! controlled grazing *** 
     is_a http://aims.fao.org/aos/agrovoc/c_bac66d94 ! grazing contracts *** 
    is_a http://aims.fao.org/aos/agrovoc/c_6663 ! rotational grazing *** 
    is_a http://aims.fao.org/aos/agrovoc/c_7456 ! strip grazing *** 
    is_a http://aims.fao.org/aos/agrovoc/c_7686 ! tethered grazing *** 
```

But we represent systems as material entities (think nervous system). I think a processual representation is better for us, but just throwing this out as an option, cc @pbuttigieg
