### ISSUE TITLE
NTR: cropping phase of shifting cultivation

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#161]
Term: cropping phase of shifting cultivation
Definition: 
Source: Sinclair, F.L., 1999. A general classification of agroforestry practice. Agroforestry systems, 46(2), pp.161-180.
Parent: AGRO:00000516
Related: AGRO:00000584, trees and crops, crops on tree-land, natural forest/tree cover, cropping phase of shifting cultivation,
ORCID: https://orcid.org/0000-0003-3985-4911

**Comment by KrishnaTO** [comment]
update label in commit to 'cropping phase of shifting cultivation'

**Comment by celineaubert** [comment]
added as shifting cultivation
