### ISSUE TITLE
create pattern for area density of X

### ISSUE THREAD

**Issue by marieALaporte** [AgriculturalSemantics/agro#24]
![image](https://cloud.githubusercontent.com/assets/5664149/25666737/a258e4a4-3021-11e7-858f-a6b035794099.png)

**Comment by pbuttigieg** [comment]
This is a strange family of classes as the "densities" are not measured, but inferred based on the amount of some substance distributed over some area. It's not exactly a quality of an area, more a 'guess'.

Some sort of axiomatisation based on ENVO:`surface layer` and material may work

**Comment by marieALaporte** [comment]
@KrishnaTO worked on those [here](https://github.com/AgriculturalSemantics/agro/pull/123). Close when merged #123
