### ISSUE TITLE
Create AP for "preferred fieldbook label"

### ISSUE THREAD

**Issue by pbuttigieg** [AgriculturalSemantics/agro#26]
e.g. 
label: experimental trial
'preferred fieldbook label': agronomic trial

**Comment by marieALaporte** [comment]
@pbuttigieg should it be a subproperty of rdfs:label? does the obo foundry provide any guidelines about that?

**Comment by marieALaporte** [comment]
@brianjlowe the ID of the property is http://purl.obolibrary.org/obo/AGRO_01000022

**Comment by pbuttigieg** [comment]
>@pbuttigieg should it be a subproperty of rdfs:label? does the obo foundry provide any guidelines about that?

We'll have it as a sibling for now, as not all labels are fieldbook preferred.
