### ISSUE TITLE
NTR: weed role (or quality)

### ISSUE THREAD

**Issue by cmungall** [AgriculturalSemantics/agro#30]
synonym: weed

we can then have accompanying OWL bridge axioms for `Quackgrass SubClassOf has-role some weed role`

Alternatively, this could be represented as a quality and we should make a PATO NTR. If weediness is an inherent property based on sub-properties like ability to invade, resilience then PATO. If it's more of a human-centric value judgment then role

**Comment by pbuttigieg** [comment]
+1 for role
