### ISSUE TITLE
NTR: grazing

### ISSUE THREAD

**Issue by pbuttigieg** [AgriculturalSemantics/agro#32]
Hello AgrO!

@TaskeHAMANO and I would like to request the addition of terms related to controlled grazing. 

Grazing itself should probably go into an animal behaviour ontology like NBO, but any techniques to control it could/should go into AgrO. 

We'd like to import it to axiomatise and better define ENVO classes like `grazed land` or `tended pasturable land`.

Would this work?

**Comment by celineaubert** [comment]
Hi,
Would this class works: AGRO:00000426?
