### ISSUE TITLE
NTR: ploughing process

### ISSUE THREAD

**Issue by pbuttigieg** [AgriculturalSemantics/agro#34]
Linked to #33 
We'd like a class to express ploughing activities to axiomatise arable land.

This would need the creation of a class for plough (syn: plow) too

proposed def: "A process during which a plough is mechanically drawn through soil to prepare it for seed sowing or planting"
dbxref: https://en.wikipedia.org/wiki/Plough
syn:

**Comment by celineaubert** [comment]
ploughing process = tillage. I have added the synonym to the class '['Tillage''](http://purl.obolibrary.org/obo/AGRO_00000002)
