### ISSUE TITLE
Naked terms

### ISSUE THREAD

**Issue by pbuttigieg** [AgriculturalSemantics/agro#36]
![image](https://user-images.githubusercontent.com/2276146/40000332-d8aecf40-578b-11e8-8d0a-2fc449c99169.png)

![image](https://user-images.githubusercontent.com/2276146/40000357-e9af1d0e-578b-11e8-89e2-bf8a9c05f690.png)

Some classes, including orphan classes, don't have labels. This should be rectified with explicit imports of those GO and IAO (and other?) terms.

**Comment by marieALaporte** [comment]
fixed. Should be good for the next release
There is just this ENVO_01001784 term that is dangling, but looking at the envo-edit file that I think it should be solved at your next release @pbuttigieg ?
