### ISSUE TITLE
Orphan classes

### ISSUE THREAD

**Issue by pbuttigieg** [AgriculturalSemantics/agro#37]
A bunch of classes are present at the top level, when several should be in deeper hierarchies. Would be good to find out why. We have some mysterious artifacts like this in ENVO, but it may be more straightforward to fix here:

![image](https://user-images.githubusercontent.com/2276146/40000497-39ec6876-578c-11e8-9602-26ce37932a64.png)

For the PCO:`collection of organisms`, this could be because of an old BFO version:

```
    <!-- http://purl.obolibrary.org/obo/PCO_0000000 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/PCO_0000000">
        <rdfs:label xml:lang="en">collection of organisms</rdfs:label>
        <owl:equivalentClass>
            <owl:Class>
                <owl:intersectionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://www.ifomis.org/bfo/1.1/snap#ObjectAggregate"/>
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0002351"/>
                        <owl:allValuesFrom rdf:resource="http://purl.obolibrary.org/obo/CARO_0001010"/>
                    </owl:Restriction>
                    <owl:Restriction>
--
        <rdfs:subClassOf rdf:resource="http://www.ifomis.org/bfo/1.1/snap#ObjectAggregate"/>
        <obo:IAO_0000115 xml:lang="en">A material entity that consists of two or more organisms, viruses, or viroids.</obo:IAO_0000115>
    </owl:Class>

```
The latest PCO version has it as a subclass of `http://purl.obolibrary.org/obo/BFO_0000027` rather than `http://www.ifomis.org/bfo/1.1/snap#ObjectAggregate`

**Comment by celineaubert** [comment]
For the classes created in AgrO, it's because we haven't agree on the hierarchy.

**Comment by celineaubert** [comment]
resolved in last release
