### ISSUE TITLE
 fertilizer basal application: misclassified

### ISSUE THREAD

**Issue by pbuttigieg** [AgriculturalSemantics/agro#38]
`fertilizer basal application` is a planned process and its definition confirms this:
> A broadcast application in which fertilizer is applied to an area before planting or before seedling emergence. 

Right now, it's under IAO classes, which is not correct.

**Comment by pbuttigieg** [comment]
The same is true for http://purl.obolibrary.org/obo/AGRO_00000042
this should be a process and a new class for the method with a definition that describes a method should be added.

**Comment by celineaubert** [comment]
moved to planned process
