### ISSUE TITLE
New "unit": Count per square meter

### ISSUE THREAD

**Issue by frostbytten** [AgriculturalSemantics/agro#39]
I don't know at what level this could be implemented, but there is a need for a count per square meter (for example, plant population) as a unit. How could this be handled?

**Comment by ddooley** [comment]
This unit can be requested of the Unit Ontology: https://www.ebi.ac.uk/ols/search?q=count&ontology=uo at their issues board: https://github.com/bio-ontology-research-group/unit-ontology/issues .  They have an additional curator so things should move along a bit more.

**Comment by KrishnaTO** [comment]
Added PR in bio-ontology-research-group/unit-ontology#40 including term 'count per square meter'
