### ISSUE TITLE
Synonym request for hand picking process & definition query

### ISSUE THREAD

**Issue by richardostler** [AgriculturalSemantics/agro#43]
Please can "hand roguing" be added as a synonym for [hand picking process](http://purl.obolibrary.org/obo/AGRO_00000217)

Also the definition states the process to be  

> A mechanical pest removal process in which unwanted organisms are removed by hands.

I think this would make more sense if "manual" replaced "mechanical".

**Comment by celineaubert** [comment]
will be available in the next release
