### ISSUE TITLE
New agricultural implement class request "tedder"

### ISSUE THREAD

**Issue by richardostler** [AgriculturalSemantics/agro#45]
Please consider adding "tedder" as an agricultural implement

**Preferred Name** tedder

**Definition** A machine used in haymaking. It is used after cutting and before windrowing, and uses moving forks to aerate or "wuffle" the hay and thus speed up the process of hay-making. The use of a tedder allows the hay to dry ("cure") better

**Participates in** [haymaking process](http://purl.obolibrary.org/obo/AGRO_00000462) - although I can see there is a specialist windrowing process which participates in haymaking process, so should there also be a "tedding process" which participates in haymaking process?

**Depends on** [motorized traction](http://purl.obolibrary.org/obo/AGRO_00000239), [animal traction](http://purl.obolibrary.org/obo/AGRO_00000240)

**Reference** https://en.wikipedia.org/wiki/Tedder_(machine)

**Comment by celineaubert** [comment]
will be available in the next release
