### ISSUE TITLE
New agricultural implement class request "combine harvester"

### ISSUE THREAD

**Issue by richardostler** [AgriculturalSemantics/agro#46]
Please consider adding combine harvester as a subclass of harvest implement.

**preferred name** combine harvester

**subclass of** [harvest implement] (http://purl.obolibrary.org/obo/AGRO_00000234)

**definition** an agricultural machine that reaps, threshes, and cleans a crop in one operation.

**participates in** [harvesting process](http://purl.obolibrary.org/obo/AGRO_00000025)

**produces** [motorized traction](http://purl.obolibrary.org/obo/AGRO_00000239)

**reference** https://en.wikipedia.org/wiki/Combine_harvester

**Comment by celineaubert** [comment]
will be available in the next release
