### ISSUE TITLE
Synonym request for "mowing"

### ISSUE THREAD

**Issue by richardostler** [AgriculturalSemantics/agro#48]
Please consider "topping" as a synonym for [mowing process](http://purl.obolibrary.org/obo/AGRO_00000220). 

Also, the definition for mowing process includes:  

>It can be used to reduce weed seed populations or restrict the growth of weeds. 

I think this is too specific as topping can also be done to prevent seeding by cover crops or as preparatory to lifting root crops.

**Comment by celineaubert** [comment]
will be available in the next release
