### ISSUE TITLE
New planned process class request "desiccation process"

### ISSUE THREAD

**Issue by richardostler** [AgriculturalSemantics/agro#49]
Please consider adding "dessication process" as subclass of planned process

**preferred name** desiccation process

**definition** application of a chemical such as a herbicide to a crop in order to destroy and reduce green crop foliage or assist crop drying as a preparatory step to harvesting.

**subclass of** [planned process](http://purl.obolibrary.org/obo/OBI_0000011)

**Comment by celineaubert** [comment]
will be available in the next release
