### ISSUE TITLE
Irrigation quantity definition problem

### ISSUE THREAD

**Issue by celineaubert** [AgriculturalSemantics/agro#5]
This definition is unclear. It is not clear what is being measured and what this data is about. We have to speak with a domain expert.

**Comment by celineaubert** [comment]
Have to import UO mm and change the unit

**Comment by cmungall** [comment]
Also, are you sure you want to model it as a data item (the measurement)? You may get more reasoning power by modeling it as a quality (the thing that is measured). It depends on the use cases for Agro

**Comment by celineaubert** [comment]
Term could be added under the PATO class : ''volume'' - http://purl.obolibrary.org/obo/PATO_0000918
Name: volume of irrigation water

Def: Volume of water applied during an irrigation process.


Exactsyn:
- quantity of irrigation water
- irrigation depth
- amount of irrigation water


@KrishnaTO Remove the link to ''length'' and ''quantity'' classes
- term has to be liked to '' irrigation process'', ''irrigation water''
- occurs in a agricultural field and experimental plot
- Units are: mm, m3, m3/ha (if it exists in UO)
