### ISSUE TITLE
NTR: bare fallow land

### ISSUE THREAD

**Issue by richardostler** [AgriculturalSemantics/agro#52]
Please can bare fallow land be added as a subclass of [fallow land](http://purl.obolibrary.org/obo/AGRO_00000390). 
**definition** An agricultural field that is set aside for a period of time and kept free from vegetation by cultivation. 

Since a bare fallow has to be maintained through cultivation should the class include the related form _has_participant,_ [tillage process](http://purl.obolibrary.org/obo/AGRO_00000223)?

**Comment by marieALaporte** [comment]
'bare fallow land' and 'tillage process' have been linked as follow:
'fallow land' and 'output of' some ('tillage process' and 'has input' some 'fallow land')
Let me know if that makes sense to you @richardostler
