### ISSUE TITLE
Tillage types required for MIxS soil package

### ISSUE THREAD

**Issue by cmungall** [AgriculturalSemantics/agro#62]
MIxS has the following value set for the MIxS term 'tillage', which is intended to specify the tillage method

[drill\|cutting   disc\|ridge till\|strip tillage\|zonal tillage\|chisel\|tined\|mouldboard\|disc   plough]

 I'm starting mapping these here:

 * AGRO:00000030 ! ridge-till
 * TODO

We have 'drill' as an object in AGRO, but should we also add drill tillage as a process?

**Comment by richardostler** [comment]
@cmungall I'm glad this has been raised, but you may have opened a small can of worms! Looking at the list you've provided, I think there are a mix of processes and equipment types that all relate to tillage. For example ridge till|strip tillage|zonal tillage|tined I think are processes whereas the others represent equipment/machinery types used in these processes. Some of these also have narrower concepts - tines, is a good example and the type of tine may also indicate its use (tillage, mechanical weed control or both) - I also think tine is also a narrower concept of harrow.

For drilling, our use case would be 'seed drill' as the type of machinery used, and 'seed drilling' as the process. But, it can be more complicated. We have several different seed drills and these will manipulate the soil/seedbed differently. So I think drilling is a seeding process, but the drill equipment used may also perform tillage processes. It seems wrong to describe a no-till seed drill as performing a tillage process, even if it is opening up the soil to lay the seed!

I'm also seeing a few cases where our farmers log processes by the machinery used, particularly where one piece of equipment is performing multiple processes. a good example is the Simba cultipress - our farmers now talk about 'cultipressing' as the process. In fact the cultipress is a branded machine which combines 3 different process (tillage using tines, DD rings to further break up soil clods (cultipacking) and a levelling board)

Agrovoc has a more comprehensive list of terms http://agrovoc.uniroma2.it/agrovoc/agrovoc/en/page/c_7771

**Comment by KrishnaTO** [comment]
Was this issue still pending or up for discussion? Did we need to add additional terms from AGROVAC? If so, please feel free to let me know by reopening this issue or describing terms to be added in the newer AGROVAC importing issue/task #132
