### ISSUE TITLE
Drainage classes needed for MIxS soil package

### ISSUE THREAD

**Issue by ukaraoz** [AgriculturalSemantics/agro#63]
MIxS has the key "drainage_class", to represent USDA drainage classes, with the following value set: [very poorly|poorly|somewhat poorly|moderately well|well|excessively drained|somewhat excessively] as defined here by [USDA](https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcseprd1296622&ext=pdf).
Should these be subclassed as "physical quality" of soil?

**Comment by KrishnaTO** [comment]
Hey @ukaraoz, 

I'm working to resolve the open issues.

Adding generic qualitative measures is not recommended practice. It's better to use quantitative results to measure drainage than to describe a process using weak categorical labels. If for instance we had an universally accepted range to define 'poorly' and 'moderately well', then it would warrant additional consideration.

 Please reopen the issue if you have additional points to consider and we can discuss further. Apologies for the delay.
