### ISSUE TITLE
NTR: "sustainable agriculture"

### ISSUE THREAD

**Issue by ddooley** [AgriculturalSemantics/agro#66]
label: **sustainable agriculture**
definition: A method of production using processes that are non-polluting, conserve non-renewable energy and natural resources, are economically efficient, are safe for workers, communities and consumers, and do not compromise the needs of future generations.
definition source: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/288329/11-546-future-of-food-and-farming-report.pdf

**Comment by ddooley** [comment]
@pbuttigieg @celineaubert Does AGRO want this, or should it go into SDGIO, or ENVO or FoodOn?

**Comment by celineaubert** [comment]
@ddooley, sorry for my late answer. It could go in AgrO if we all agree. Do you think it could fit as a ''plan specification''?

**Comment by ddooley** [comment]
I think it is more of an OBI "objective specification"?  Now AGRO involves just agronomy right?  So over to @pbuttigieg if he wants to see it in SDGIO?
[Edit]: I realize now the term label needs to be clarified - probably "sustainable agriculture process", which begs a second "sustainable agriculture goal" term too.  One points to compatible processes while the other points to the objectives the processes need to satisfy.

**Comment by elizabetharnaud** [comment]
I would place 'sustainable agriculture goal' in SDGiO  because this  implies  existence of agronomic, ecological, socioeconomic & legal processes along the value chain that can be monitored over time and at large scale.  ' Sustainable agriculture process" could be in Agro as  a production system at the farm scale.

**Comment by ddooley** [comment]
Ok, sounds good, so then for AGRO:
**label: sustainable agriculture process**

**Comment by ddooley** [comment]
Any objections to the definition or definition source? I realize defining sustainable processes is ambitious!

**Comment by ddooley** [comment]
Do you happen to have an AGRO id for this term ready?

**Comment by celineaubert** [comment]
@ddooley sorry, I have added a comment in GitHub desktop that did not reach GitHub online! Here it is: 
I've added sustainable agriculture process class
(http://purl.obolibrary.org/obo/AGRO_00000515) under planned process,
and kept your suggested defintion for now. We can update later if we
found a better one!
