### ISSUE TITLE
New subclass term of area density: animal manure area density

### ISSUE THREAD

**Issue by tscottm** [AgriculturalSemantics/agro#69]
Suggested Revision:
"animal manure area density" defined as "An area density quality which inheres in animal manure by virtue of some influence exerted by the mass of animal manure applied in a given surface area."  This new term would be a subclass of "area density" [http://purl.obolibrary.org/obo/PATO_0001351].

Rationale:
"animal manure" [http://purl.obolibrary.org/obo/AGRO_00000079] is an organic fertilizer that can be applied to given unit area, just like other nutrients listed under "area density," such as phosphorus [http://purl.obolibrary.org/obo/AGRO_00000160].

**Comment by celineaubert** [comment]
Dear Scott, the term has been added. It will be available in next
release. In the mean time you can use its
URI: http://purl.obolibrary.org/obo/AGRO_00000514
