### ISSUE TITLE
Revised definition of single superphosphate

### ISSUE THREAD

**Issue by tscottm** [AgriculturalSemantics/agro#70]
Current Definition:
"A fertilizer that is obtained by acid chemical attack of a phosphate rock with sulfuric acid. It contains 16 to 20% P2O5. It comes in the form of grey granules. [hasDbXref: http://agropedia.iitk.ac.in/content/water-soluble-phosphatic-fertilizers]"
[http://purl.obolibrary.org/obo/AGRO_00002064]

Suggested Revision:
"A product made by reaction of phosphate rock with sulfuric acid, usually containing 7 to 10% P (16 to 22% P2O5), composed of monocalcium phosphate, Ca(H2PO4)2, and gypsum, CaSO4."
Synonyms: normal superphosphate, ordinary superphoshate

Rationale:
The current definition uses a citation that itself has no citations and does not represent scientific consensus. The suggested revision originates from the definition of "superphosphate, normal" in the Glossary of Soil Science Terms [https://www.soils.org/publications/soils-glossary] and has been appended with chemical information originating from: Nunn RJ, Dee TP (1954) Superphosphate production: the influence of various factors on the speed of reaction and the composition of the product. Journal of the Science of Food and Agriculture 5:257-265. https://doi.org/10.1002/jsfa.2740050601

**Comment by celineaubert** [comment]
Thank you Scott for updating the definition. Changes will be available in the next release.
