### ISSUE TITLE
Agricultural Field Ownership / Rental

### ISSUE THREAD

**Issue by oldskeptic** [AgriculturalSemantics/agro#76]
What mechanism is Agro using for representing the ownership of an Agricultural Field or it (rental) usage by a farmer?

**Comment by KrishnaTO** [comment]
Hi @oldskeptic,

I'm working on resolving the old issues. 

Field Ownership / Rental are very localised concepts, better declared using non-Ontology variables. The goal of an Ontology is to describe universal semantic and logical inferences, and [Person](http://purl.obolibrary.org/obo/NCIT_C25190) may be the closest. 

If there are use-cases you can describe where field ownership / rental would play an universal role as part of the model, we'd be happy to discuss further. Please reopen the issue if you'd like to do so.

**Comment by oldskeptic** [comment]
Please re-read my question. 

Given an arbitrary instance of an agricultural field, how do you assign ownership (from which any rights to perform operations and experiments come from) to an arbitrary Person, Org, etc...

**Comment by KrishnaTO** [comment]
There aren't any existing mechanisms in place to assign ownership or specify owned or rented fields.
