### ISSUE TITLE
NTR Controlled Traffic

### ISSUE THREAD

**Issue by peetmate** [AgriculturalSemantics/agro#79]
Proposed definition: "Controlled traffic farming is a system which confines all machinery loads to the least possible area of permanent traffic lanes. The permanent traffic lanes are normally parallel to each other and this is the most efficient way of achieving CTF, but the definition does not preclude tracking at an angle. The permanent traffic lanes may be cropped or non-cropped depending on a wide range of variables and local constraints.

It does not include a prescription for tillage although most growers adopting CTF use little or none because soil structure does not need to be repaired."

Note that I took this definition from wikipedia.

https://qcat.wocat.net/en/wocat/technologies/view/technologies_945/
https://en.wikipedia.org/wiki/Controlled_traffic_farming

The placement of the term is a bit challenging as it links to multiple agricultural processes.

**Comment by celineaubert** [comment]
HiI Peter, 
thanks for the term request. The term has been added. The URI is : AGRO_00000565
