### ISSUE TITLE
Travis Build failure

### ISSUE THREAD

**Issue by pbuttigieg** [AgriculturalSemantics/agro#8]
Similar to the [current failure](https://travis-ci.org/FoodOntology/foodon#L215) in FOODON https://github.com/FoodOntology/foodon/issues/1, the build failed on incompatible major minor versions with java when trying to mirror with owltools. 

We were using a python environment, but then switched to a java env ([see here](https://github.com/AgriculturalSemantics/agro/commit/b28177cf5edbe40a062808e319bdd42fe7e2e984)) so we could specify which version of java we wanted to run.

Occasionally, we will get a `build passing` status when there's no owltools-driven mirroring to be done. 

It seems the OWL API used by owltools needs Java 8, so we' ll try this next. See https://github.com/AgriculturalSemantics/agro/commit/6a66692a2fbbf823a30d08873084b5560af9391d and https://github.com/AgriculturalSemantics/agro/commit/05de0cbc1a0a6d47d55d65fe68af672d4fa47564 (the latter for oracle jdk 8)

@cmungall, may be of interest to you.

**Comment by marieALaporte** [comment]
possibly related to [this](https://github.com/ontodev/robot/issues/56)

**Comment by marieALaporte** [comment]
running a make test on our local machine worked fine

**Comment by marieALaporte** [comment]
I tried to run travis using oraclejdk8 after a term in the file src/ontology/imports/chebi_terms.txt and I got this message: 
make: Nothing to be done for `test'. 
I tested with different targets (all, all_imports, test) and  got the same message

When I run travis using oraclejdk7 or openjdk7, the build fails with the message Unsupported major.minor version 52.0

**Comment by cmungall** [comment]
It will only try to rebuild the imports if the _terms.txt file has a more recent timestamp
