### ISSUE TITLE
[NTR] Inorganic fertiliser role

### ISSUE THREAD

**Issue by KrishnaTO** [AgriculturalSemantics/agro#95]
**Preferred term label:**
Inorganic fertiliser role

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
A fertilizer that is derived of one or more of nitrogen, phosphorus, and potassium.
https://www.brenntag.com/en-us/industries/agriculture/guide-to-fertilizers/
https://www.britannica.com/topic/fertilizer

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/AgrO), or your favorite ontology browser)**
[role](http://purl.obolibrary.org/obo/BFO_0000023)

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Comment by KrishnaTO** [comment]
Review necessity for term as branch-[batch-fertilizer-concentrations](https://github.com/KrishnaTO/agro/tree/batch-fertilizer-concentrations) creates chemical area densities

**Comment by celineaubert** [comment]
HI Krishna, 

The current definition could also be applied to organic fertilizers. I would therefore change the definition for:
A role that inheres in a material entity that is mined from mineral deposits or manufactured from synthetic compounds and that excludes carbon-containing materials except ureas. 
https://en.wikipedia.org/wiki/Fertilizer

**Comment by KrishnaTO** [comment]
Pushed to branch [Batch fertilizer concentrations](https://github.com/AgriculturalSemantics/agro/pull/123); awaiting merge

**Comment by KrishnaTO** [comment]
Ignore last commit, duplicate of previous commit. 

Closing due to PR added.
